name: Stream1

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'  #

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Run Stream from Secret
        env:
          S_URL: ${{ secrets.S_URL }}
          R_URL: ${{ secrets.R_URL }}
        run: |
          echo "Starting..." && \
          ffmpeg -re -i "$S_URL" -c copy -f flv "$R_URL" & \
          STREAM_PID=$!; \
          echo "PID=$STREAM_PID"; \
          sleep 7200; \
          echo "Stopping Stream..."; \
          kill $STREAM_PID
